
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp;

// Create single instance of sample data from first line of dataset for model input
MLModel.ModelInput sampleData = new()
{
    Url = @"mp3raid.com/music/krizz_kaliko.html",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Type with predicted Type from sample data...\n\n");


Console.WriteLine($"Url: {@"mp3raid.com/music/krizz_kaliko.html"}");
Console.WriteLine($"Type: {@"benign"}");


Console.WriteLine($"\n\nPredicted Type: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

