
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace UrlClassifier_ML
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            UrlClassifier.ModelInput sampleData = new UrlClassifier.ModelInput()
            {
                Url = @"br-icloud.com.br",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = UrlClassifier.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Type with predicted Type from sample data...\n\n");


            Console.WriteLine($"Url: {@"br-icloud.com.br"}");
            Console.WriteLine($"Type: {@"phishing"}");


            Console.WriteLine($"\n\nPredicted Type: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
